output "resource_group_name" {
  description = "Resource group containing the application."
  value       = azurerm_resource_group.app.name
}

output "web_app_name" {
  description = "Web App name for a separate application ZIP deployment."
  value       = azurerm_linux_web_app.app.name
}

output "web_app_url" {
  description = "Application HTTPS endpoint."
  value       = "https://${azurerm_linux_web_app.app.default_hostname}"
}

output "plan_resource_id" {
  description = "App Service Plan resource ID."
  value       = azurerm_service_plan.app.id
}

output "web_app_resource_id" {
  description = "Web App resource ID."
  value       = azurerm_linux_web_app.app.id
}

output "principal_id" {
  description = "System-assigned identity ID, generated by Azure."
  value       = azurerm_linux_web_app.app.identity[0].principal_id
}